services:
  db:
    image: postgres:14
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_PORT: ${DATABASE_PORT}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    ports: 
      - "6379:6379"

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command:
      - /start-django.sh
    volumes:
      - .:/app
      - static_volume:/app/backend/django_static
    ports:
      - "${DJANGO_PORT}:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command:
      - /start-celery-worker.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    command:
      - /start-celery-beat.sh
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  

volumes:
  static_volume: {}
  postgres_data: {}
