# Generated by Django 4.2.14 on 2024-07-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploader', '0002_upload_delete_fileupload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='upload',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='upload',
            name='filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='filetype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
