# Generated by Django 4.2.14 on 2024-07-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_upload_options_upload_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='filetype',
        ),
    ]
