# Generated by Django 5.0.7 on 2024-07-24 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_upload_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['-uplo_uploaded_at'], 'verbose_name': 'Upload', 'verbose_name_plural': 'Uploads'},
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='description',
            new_name='uplo_description',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='uplo_file',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='filename',
            new_name='uplo_filename',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='filesize',
            new_name='uplo_filesize',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_at',
            new_name='uplo_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='uplo_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
