# Generated by Django 5.0.7 on 2024-07-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_upload_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_login',
            new_name='uspr_first_login',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='uspr_user',
        ),
    ]
