# Generated by Django 5.0.7 on 2024-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_fileversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pere_username', models.CharField(max_length=150, unique=True)),
                ('pere_email', models.EmailField(max_length=254, unique=True)),
                ('pere_hashed_password', models.CharField(max_length=128)),
                ('pere_created_at', models.DateTimeField(auto_now_add=True)),
                ('pere_activation_token', models.CharField(max_length=255)),
                ('pere_is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='FileVersion',
        ),
    ]
